package com.example.taskmate.entity;

public class MStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_status.status_code
     *
     * @mbg.generated
     */
    private String statusCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_status.status_name
     *
     * @mbg.generated
     */
    private String statusName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_status.status_code
     *
     * @return the value of m_status.status_code
     *
     * @mbg.generated
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_status.status_code
     *
     * @param statusCode the value for m_status.status_code
     *
     * @mbg.generated
     */
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode == null ? null : statusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_status.status_name
     *
     * @return the value of m_status.status_name
     *
     * @mbg.generated
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_status.status_name
     *
     * @param statusName the value for m_status.status_name
     *
     * @mbg.generated
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName == null ? null : statusName.trim();
    }
}