package com.example.taskmate.entity;

public class TMemo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_memo.memo_id
     *
     * @mbg.generated
     */
    private Integer memoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_memo.task_id
     *
     * @mbg.generated
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_memo.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_memo.memo_id
     *
     * @return the value of t_memo.memo_id
     *
     * @mbg.generated
     */
    public Integer getMemoId() {
        return memoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_memo.memo_id
     *
     * @param memoId the value for t_memo.memo_id
     *
     * @mbg.generated
     */
    public void setMemoId(Integer memoId) {
        this.memoId = memoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_memo.task_id
     *
     * @return the value of t_memo.task_id
     *
     * @mbg.generated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_memo.task_id
     *
     * @param taskId the value for t_memo.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_memo.memo
     *
     * @return the value of t_memo.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_memo.memo
     *
     * @param memo the value for t_memo.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}