package com.example.taskmate.entity;

import java.util.Date;

public class TTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.task_id
     *
     * @mbg.generated
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.task_name
     *
     * @mbg.generated
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.limit_date
     *
     * @mbg.generated
     */
    private Date limitDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.status_code
     *
     * @mbg.generated
     */
    private String statusCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.task_id
     *
     * @return the value of t_task.task_id
     *
     * @mbg.generated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.task_id
     *
     * @param taskId the value for t_task.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.task_name
     *
     * @return the value of t_task.task_name
     *
     * @mbg.generated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.task_name
     *
     * @param taskName the value for t_task.task_name
     *
     * @mbg.generated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.limit_date
     *
     * @return the value of t_task.limit_date
     *
     * @mbg.generated
     */
    public Date getLimitDate() {
        return limitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.limit_date
     *
     * @param limitDate the value for t_task.limit_date
     *
     * @mbg.generated
     */
    public void setLimitDate(Date limitDate) {
        this.limitDate = limitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.status_code
     *
     * @return the value of t_task.status_code
     *
     * @mbg.generated
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.status_code
     *
     * @param statusCode the value for t_task.status_code
     *
     * @mbg.generated
     */
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode == null ? null : statusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.remarks
     *
     * @return the value of t_task.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.remarks
     *
     * @param remarks the value for t_task.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}