package com.example.taskmate.mapper;

import com.example.taskmate.entity.MStatus;
import com.example.taskmate.entity.MStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_status
     *
     * @mbg.generated
     */
    long countByExample(MStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_status
     *
     * @mbg.generated
     */
    int deleteByExample(MStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_status
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String statusCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_status
     *
     * @mbg.generated
     */
    int insert(MStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_status
     *
     * @mbg.generated
     */
    int insertSelective(MStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_status
     *
     * @mbg.generated
     */
    List<MStatus> selectByExample(MStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_status
     *
     * @mbg.generated
     */
    MStatus selectByPrimaryKey(String statusCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_status
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MStatus record, @Param("example") MStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_status
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MStatus record, @Param("example") MStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MStatus record);
}