package com.example.taskmate.mapper;

import com.example.taskmate.entity.TMemo;
import com.example.taskmate.entity.TMemoExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TMemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memo
     *
     * @mbg.generated
     */
    long countByExample(TMemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memo
     *
     * @mbg.generated
     */
    int deleteByExample(TMemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer memoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memo
     *
     * @mbg.generated
     */
    int insert(TMemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memo
     *
     * @mbg.generated
     */
    int insertSelective(TMemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memo
     *
     * @mbg.generated
     */
    List<TMemo> selectByExample(TMemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memo
     *
     * @mbg.generated
     */
    TMemo selectByPrimaryKey(Integer memoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TMemo record, @Param("example") TMemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TMemo record, @Param("example") TMemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMemo record);
}